<?php

namespace Application\Controller;

use \Zend\Mvc\Controller\AbstractActionController;
use Doctrine\ORM\EntityManager;
use Zend\Mvc\MvcEvent;

class BaseController extends AbstractActionController
{

    protected $entityManager;


    public function onDispatch(MvcEvent $e)
    {

        $this->setEntityManager($this->getServiceLocator()->get(EntityManager::class));
        return parent::onDispatch($e); // TODO: Change the autogenerated stub
    }


    public function setEntityManager(EntityManager $entityManager)
    {
        $this->entityManager = $entityManager;

    }


    public function getEntityManager()
    {

        return $this->entityManager;

    }


}