<h1>Категории</h1>
<a href="/admin/category/add/">Добавить</a><br><br>
<?php
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('
<div%s><button type="button" class="close" data-dismiss="alert" aria-hidden="true" >
&times;
</button>
<ul><li>
')
    ->setMessageSeparatorString('</li></li>')
    ->setMessageCloseString('</li></ul></div>');

echo $flash->render('error', ['alert','alert-dismissable','alert-danger']);
echo $flash->render('info',['alert','alert-dismissable','alert-info']);
echo $flash->render('defaults',['alert','alert-dismissable','alert-warning']);
echo $flash->render('success',['alert','alert-dismissable','alert-success']);

?>

<table class="table table-bordered table-hover">
    <thead>
    <tr>
        <th>#</th>
        <th>Ключ</th>
        <th>Название</th>
        <th>Действие</th>
    </tr>
    </thead>
    <tbody>
    <?php
    /**
     * @var $category  \Blog\Entity\Category
     */
    foreach ($categories as $category):
        ?>
        <tr>
            <td><?= $category->getId(); ?></td>
            <td><?= $category->getCategoryKey() ?></td>
            <td><?= $category->getCategoryName() ?></td>
            <td><a href="
         <?=
                $this->url('admin/category', ['action' => 'edit', 'id' => $category->getId()])
                ?>">Edit</a>
                <a href="
             <?=
                $this->url('admin/category', ['action' => 'delete', 'id' => $category->getId()])
                ?>">
                    delete
                </a></td>
        </tr>

    <?php
    endforeach;
    ?>

    </tbody>
</table>
<?php